<?php


namespace App\Shared;


class ConstantesShared
{
    const RESPOSTA_SUCESSO = 'TPR01';
    const RESPOSTA_MULTIPLOS_ERROS = 'TPR02';
    const RESPOSTA_ERRO = 'TPR03';
    const RESPOSTA_CAMPO_OBRIGATORIO = 'TPR04';
    const RESPOSTA_EMAIL_INVALIDO = 'TPR05';
    const RESPOSTA_CAMPO_EXISTE = 'TPR06';
    const RESPOSTA_NENHUM_RESULTADO = 'TPR07';
    const RESPOSTA_ENTIDADE_NAO_ENCONTRADA = 'TPR08';
}
